on:
- push
- pull_request
name: test
jobs:
  test:
    strategy:
      matrix:
        go-version:
        - 1.13.x
        platform:
        - macos-latest
        - ubuntu-latest
        - windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout
      uses: actions/checkout@v1
    - name: Go Test
      run: go test ./...