on:
- push
name: workflow
jobs:
  build:
    strategy:
      matrix:
        go-version:
        - 1.13.x
        platform:
        - macos-latest
        - ubuntu-latest
        - windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run: go build ./...
  test:
    strategy:
      matrix:
        go-version:
        - 1.13.x
        platform:
        - macos-latest
        - ubuntu-latest
        - windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout
      uses: actions/checkout@v1
    - name: Test
      run: go test ./...
  lint:
    strategy:
      matrix:
        go-version:
        - 1.13.x
        platform:
        - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install golangci-lint
      run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.20.0
    - name: Lint
      run: $(go env GOPATH)/bin/golangci-lint run ./...
  format:
    strategy:
      matrix:
        go-version:
        - 1.13.x
        platform:
        - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install gofumports
      run: GO111MODULE=off go get -u mvdan.cc/gofumpt/gofumports
    - name: Format
      run: find . -name \*.go | xargs $(go env GOPATH)/bin/gofumports -w
    - name: Check diff
      run: git diff --exit-code